import { z } from "zod";

export const reportGenerationSystemPrompt = `You are a project reporting assistant. Generate concise daily summaries in natural language suitable for WhatsApp delivery.

Keep the tone professional but friendly. Focus on:
- Key accomplishments (tasks completed)
- Work in progress (new tasks)
- Concerns that need attention (risks)
- Actionable insights for the team

Messages may be in Indonesian or English. Generate reports in the same language as the project's primary communication.

Output valid JSON only.`;

export const ReportGenerationSchema = z.object({
  narrative: z
    .string()
    .describe(
      "A concise narrative summary of the day's progress, 2-3 sentences",
    ),
  highlights: z
    .array(z.string())
    .describe("List of positive accomplishments or milestones"),
  concerns: z
    .array(z.string())
    .describe("List of issues or risks that need attention"),
});

export type ReportGenerationResult = z.infer<typeof ReportGenerationSchema>;

export function buildReportGenerationPrompt(
  projectName: string,
  stats: {
    newTasks: number;
    resolvedTasks: number;
    activeRisks: number;
    messageCount: number;
  },
  recentActivity: {
    completedTasks: string[];
    newTasks: string[];
    risks: Array<{ severity: string; explanation: string }>;
  },
): string {
  const completedTasksList =
    recentActivity.completedTasks.length > 0
      ? `\n\nCompleted tasks:\n${recentActivity.completedTasks.map((t, i) => `${i + 1}. ${t}`).join("\n")}`
      : "";

  const newTasksList =
    recentActivity.newTasks.length > 0
      ? `\n\nNew tasks:\n${recentActivity.newTasks.map((t, i) => `${i + 1}. ${t}`).join("\n")}`
      : "";

  const risksList =
    recentActivity.risks.length > 0
      ? `\n\nActive risks:\n${recentActivity.risks.map((r, i) => `${i + 1}. [${r.severity.toUpperCase()}] ${r.explanation}`).join("\n")}`
      : "";

  return `Project: ${projectName}

Daily Statistics:
- New tasks: ${stats.newTasks}
- Tasks completed: ${stats.resolvedTasks}
- Active risks: ${stats.activeRisks}
- Messages processed: ${stats.messageCount}${completedTasksList}${newTasksList}${risksList}

Generate a concise daily summary that highlights progress and flags any concerns.`;
}

export function formatReportForWhatsApp(
  projectName: string,
  date: string,
  stats: {
    newTasks: number;
    resolvedTasks: number;
    activeRisks: number;
    messageCount: number;
  },
  report: ReportGenerationResult,
): string {
  const header = `📊 *Daily Report — ${projectName}*\n📅 ${date}\n`;

  const statsSection = `✅ *Tasks Completed:* ${stats.resolvedTasks}
📋 *New Tasks:* ${stats.newTasks}
⚠️ *Active Risks:* ${stats.activeRisks}
💬 *Messages Processed:* ${stats.messageCount}\n`;

  const narrativeSection = `*Summary:*\n${report.narrative}\n`;

  const highlightsSection =
    report.highlights.length > 0
      ? `*Highlights:*\n${report.highlights.map((h) => `• ${h}`).join("\n")}\n`
      : "";

  const concernsSection =
    report.concerns.length > 0
      ? `*Concerns:*\n${report.concerns.map((c) => `⚠️ ${c}`).join("\n")}\n`
      : "";

  const footer = `---\nGenerated by Watchdog 🐕`;

  return (
    header +
    "\n" +
    statsSection +
    "\n" +
    narrativeSection +
    "\n" +
    highlightsSection +
    concernsSection +
    footer
  );
}
